pool:
  vmImage: 'ubuntu-latest'

- task: SonarQubePrepare@4
  inputs:
    scannerMode: 'CLI'
    configMode: 'file'

- task: SonarQubeAnalyze@4


- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'
